name: Jest Tests Coverage

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Install Expo CLI
              run: npm install -g expo-cli

            - name: Run Jest tests with coverage
              run: npm run test:coverage

            - name: Upload coverage to Coveralls
              uses: coverallsapp/github-action@v2.3.0
              with:
                  github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
                  path-to-lcov: coverage/lcov.info
